import type { Resources } from "./types";

export const en: Resources = {
  "nav_dashboard": "Dashboard",
  "nav_models": "Models",
  "nav_profiles": "Profiles",
  "nav_backups": "Backups",
  "nav_diagnostics": "Diagnostics",
  "nav_config": "Configuration",
  "footer_brand": "PreSett — Gentle-AI configuration manager",
  "topbar_search_placeholder": "Search PreSett…",
  "topbar_search_aria": "Search agents, models, and profiles",
  "topbar_search_clear_aria": "Clear search input",
  "topbar_theme_toggle_aria": "Toggle theme",
  "topbar_notifications_aria": "Notifications",
  "topbar_account_aria": "Account",
  "topbar_menu_aria": "Open menu",
  "topbar_menu_close_aria": "Close menu",
  "sidebar_group_menu": "Menu",
  "sidebar_group_workspace": "Workspace",
  "sidebar_sync_cta": "Sync configs",
  "sidebar_sync_error_message": "Configuration sync could not complete. Try again or check the backup service.",
  "sidebar_sync_success": "Configuration sync completed.",
  "workspace_overview": "Workspace overview",
  "dashboard_title": "Dashboard",
  "dashboard_status_title": "Status",
  "dashboard_status_description": "Gentle-AI configuration manager is ready.",
  "dashboard_status_hint": "Agent detection and sync status will appear here.",
  "dashboard_models_title": "Models",
  "dashboard_models_description": "Assign models to SDD phases and agents.",
  "dashboard_models_action": "Manage Models",
  "dashboard_profiles_title": "Profiles",
  "dashboard_profiles_description": "Create and switch OpenCode SDD profiles.",
  "dashboard_profiles_action": "Manage Profiles",
  "dashboard_backups_title": "Backups",
  "dashboard_backups_description": "View and restore Gentle-AI backups.",
  "dashboard_backups_action": "View Backups",
  "dashboard_header_description": "Manage your Gentle-AI configuration, models, profiles, and backups from one place.",
  "dashboard_stat_models_label": "Active Models",
  "dashboard_stat_profiles_label": "Total Profiles",
  "dashboard_stat_backups_label": "Backups Stored",
  "dashboard_stat_system_label": "Last Sync",
  "dashboard_quick_access_title": "Quick Access",
  "dashboard_agents_title": "Installed agents",
  "dashboard_agents_manage": "Manage all",
  "dashboard_agent_configured": "Configured",
  "dashboard_agent_partial": "Partial",
  "dashboard_agent_add": "Add agent",
  "dashboard_agent_models": "models",
  "dashboard_agent_model_label": "model",
  "dashboard_last_sync_never": "Never",
  "dashboard_status_badge": "Active",
  "quick_action_models_title": "Configure models",
  "quick_action_models_desc": "Assign models to SDD phases",
  "quick_action_profiles_title": "Switch SDD profile",
  "quick_action_profiles_desc": "gentle-orchestrator active",
  "quick_action_backups_title": "Restore backup",
  "quick_action_backups_desc": "5 snapshots available",
  "tdd_strict_mode_title": "TDD strict mode",
  "tdd_strict_mode_desc": "Tests are enforced across all SDD phases in this workspace.",
  "tdd_strict_mode_enabled": "Enabled",
  "models_title": "Models",
  "models_status_badge": "Active",
  "models_header_description": "Assign models to SDD phases and agents.",
  "models_cardTitle": "Model Assignments",
  "models_loading": "Loading model assignments…",
  "models_loadError": "Failed to load model assignments",
  "models_validationUnavailable": "Model catalog unavailable",
  "models_validationMessage": "Selections cannot be validated until the catalog loads.",
  "profiles_title": "SDD Profiles",
  "profiles_status_badge": "Active",
  "profiles_header_description": "Create and switch OpenCode SDD profiles.",
  "profiles_cardTitle": "Profiles",
  "profiles_loading": "Loading profiles…",
  "profiles_loadError": "Failed to load profiles",
  "profiles_create_title": "Create Profile",
  "profiles_create_description": "Define a new profile and assign its model orchestrator.",
  "profiles_create_placeholder": "Profile name",
  "profiles_create_required": "The orchestrator assignment is required.",
  "profiles_create_action": "Create profile",
  "profiles_orchestrator_assignment": "Orchestrator assignment",
  "profiles_assigned": "Assigned",
  "profiles_saveAssignment": "Save assignment",
  "profiles_clear": "Clear",
  "profiles_discard": "Discard",
  "profiles_active": "Active",
  "profiles_modelAssignments": "model assignment",
  "profiles_modelAssignments_plural": "model assignments",
  "profiles_switch": "Switch",
  "profiles_delete": "Delete",
  "profiles_deleteConfirm": "Delete profile \"{{name}}\"?",
  "profiles_edit": "Edit",
  "profiles_editTitle": "Edit Profile",
  "profiles_save": "Save",
  "profiles_nameHelp": "Use lowercase letters, numbers, underscores, or hyphens. Other characters are removed automatically.",
  "profiles_createDisabledHelp": "Add a valid profile name and orchestrator assignment to enable profile creation.",
  "profiles_createSuccess": "Profile created.",
  "profiles_createError": "Unable to create profile",
  "profiles_switchSuccess": "Profile switched.",
  "profiles_deleteSuccess": "Profile deleted.",
  "profiles_deleteError": "Unable to delete profile",
  "profiles_updateSuccess": "Profile updated.",
  "profiles_updateError": "Unable to update profile",
  "backups_title": "Backups",
  "backups_status_badge": "Active",
  "backups_header_description": "View and restore Gentle-AI backups.",
  "backups_cardTitle": "Backups",
  "backups_loading": "Loading backups…",
  "backups_loadError": "Failed to load backups",
  "backups_sync_title": "Sync Backups",
  "backups_sync_description": "Run a manual sync with the Gentle-AI backup store.",
  "backups_sync_action": "Run Sync",
  "backups_sync_running": "Sync running…",
  "backups_exitCode": "Exit code",
  "backups_noBackups": "No backups found",
  "backups_pinned": "Pinned",
  "backups_source": "Source",
  "backups_files": "files",
  "backups_restore": "Restore",
  "backups_pin": "Pin",
  "backups_unpin": "Unpin",
  "backups_delete": "Delete",
  "backups_cancel": "Cancel",
  "backups_deleteConfirmTitle": "Delete Backup",
  "backups_deleteConfirmDesc": "Are you sure you want to delete backup {{id}}? This action cannot be undone.",
  "backups_restoreConfirmTitle": "Restore Backup",
  "backups_restoreConfirmDesc": "This will restore backup {{id}} to its original location. Existing files may be overwritten. Continue?",
  "backups_restore_success": "Backup restored successfully.",
  "backups_delete_success": "Backup deleted successfully.",
  "backups_sync_success": "Backup sync completed.",
  "backups_sync_failed": "Backup sync failed.",
  "backups_pin_success": "Backup pinned.",
  "backups_unpin_success": "Backup unpinned.",
  "modelPicker_provider": "Provider",
  "modelPicker_model": "Model",
  "modelPicker_variant": "Variant",
  "modelPicker_save": "Save Assignment",
  "agentAssignment_unset": "unset",
  "agentAssignment_edit": "Edit assignment",
  "errors_generic": "Error",
  "dashboard_partial_error": "Some services could not be loaded. Showing available data.",
  "models_activeProfile": "Active Profile",
  "models_syncNow": "Sync Now",
  "models_resetAll": "Reset All",
  "models_resetConfirmTitle": "Reset All Assignments",
  "models_resetConfirmDesc": "This will reset all model assignments to their original values. Continue?",
  "models_syncSuccess": "Sync completed successfully",
  "models_assignmentSaved": "Assignment saved.",
  "models_assignmentSaveError": "Unable to save assignment",
  "models_profileSwitched": "Profile switched.",
  "models_profileSwitchError": "Unable to switch profile",
  "models_resetSuccess": "Assignments reset.",
  "models_emptyAssignmentsTitle": "No agent assignments found",
  "models_emptyAssignmentsDesc": "Sync configs or create an assignment source so models can appear here.",
  "diagnostics_update_notice": "Gentle-AI {{version}} is available on {{channel}}.",
  "diagnostics_check_now": "Check Gentle-AI releases now",
  "diagnostics_checking": "Checking releases…",
  "diagnostics_title": "Diagnostics",
  "diagnostics_status_badge": "Local",
  "diagnostics_header_description": "Review safe Gentle-AI status and release availability without exposing local paths.",
  "diagnostics_loading": "Loading diagnostics…",
  "diagnostics_load_error": "Diagnostics could not be loaded.",
  "diagnostics_cli_title": "Gentle-AI CLI",
  "diagnostics_config_title": "Configuration",
  "diagnostics_state_title": "State",
  "diagnostics_routes_title": "Canonical routes",
  "diagnostics_installed": "Installed",
  "diagnostics_unavailable": "Unavailable",
  "diagnostics_available": "Available",
  "diagnostics_route_config": "Configuration file",
  "diagnostics_route_state": "State file",
  "diagnostics_route_backups": "Backups directory",
  "diagnostics_exists": "Exists",
  "diagnostics_readable": "Readable",
  "diagnostics_writable": "Writable",
  "diagnostics_yes": "Yes",
  "diagnostics_no": "No",
  "diagnostics_releases_title": "Gentle-AI releases",
  "diagnostics_stable": "Stable",
  "diagnostics_rc": "Release candidate",
  "diagnostics_no_update": "No pending update",
  "diagnostics_check_error": "Release check could not complete.",
  "config_title": "Global configuration",
  "config_description": "Manage Gentle-AI and OpenCode preferences independently.",
  "config_loading": "Loading configuration…",
  "config_load_error": "Configuration could not be loaded.",
  "config_status_ready": "Configured",
  "config_status_incomplete": "Needs setup",
  "config_gentle_title": "Gentle-AI",
  "config_gentle_description": "Set the response language and persona for this workspace.",
  "config_gentle_status": "Workspace",
  "config_language": "Response language",
  "config_persona": "Persona",
  "config_gentle_save": "Save Gentle-AI",
  "config_gentle_saved": "Gentle-AI configuration saved.",
  "config_gentle_error": "Gentle-AI configuration could not be saved.",
  "config_opencode_title": "OpenCode",
  "config_opencode_description": "Choose the default agent assignment for OpenCode.",
  "config_agent": "Agent",
  "config_provider": "Provider",
  "config_model": "Model",
  "config_variant": "Variant",
  "config_catalog_error": "The model catalog is unavailable. Model configuration is disabled.",
  "config_opencode_save": "Save OpenCode",
  "config_opencode_saved": "OpenCode configuration saved.",
  "config_opencode_error": "OpenCode configuration could not be saved.",
  "config_field_required": "This field is required.",
  "search_title": "Global search",
  "search_status_badge": "Local",
  "search_header_description": "Find agents, models, profiles, backups, and safe configuration fields from one page.",
  "search_empty_title": "Search everything in PreSett",
  "search_empty_description": "Search agents, models, profiles, backups, and safe configuration fields.",
  "search_loading": "Searching…",
  "search_no_results": "No results found for \"{{query}}\".",
  "search_error_fallback": "Search could not be loaded.",
  "search_partial_warning": "Some search sources were unavailable: {{sources}}.",
  "search_group_agent": "Agents",
  "search_group_model": "Models",
  "search_group_profile": "Profiles",
  "search_group_backup": "Backups",
  "search_group_config": "Configuration",
  "search_pinned": "Pinned",
  "search_active": "Active",
  "notif_update_title": "Update available",
  "notif_update_available": "Gentle AI {{version}} is ready to install.",
  "notif_panel_title": "Notifications",
  "notif_panel_empty": "No notifications yet.",
  "notif_item_dismiss_aria": "Dismiss",
};
