import type { Resources } from "./types";

export const en: Resources = {
  "nav_dashboard": "Dashboard",
  "nav_models": "Models",
  "nav_profiles": "Profiles",
  "nav_backups": "Backups",
  "footer_brand": "PreSett — Gentle-AI configuration manager",
  "topbar_search_placeholder": "Search agents, models, profiles…",
  "topbar_search_aria": "Search agents, models, and profiles",
  "topbar_theme_toggle_aria": "Toggle theme",
  "topbar_notifications_aria": "Notifications",
  "topbar_account_aria": "Account",
  "topbar_menu_aria": "Open menu",
  "topbar_menu_close_aria": "Close menu",
  "sidebar_group_menu": "Menu",
  "sidebar_group_workspace": "Workspace",
  "sidebar_sync_cta": "Sync configs",
  "sidebar_sync_error_message": "Configuration sync could not complete. Try again or check the backup service.",
  "sidebar_sync_success": "Configuration sync completed.",
  "workspace_overview": "Workspace overview",
  "dashboard_title": "Dashboard",
  "dashboard_status_title": "Status",
  "dashboard_status_description": "Gentle-AI configuration manager is ready.",
  "dashboard_status_hint": "Agent detection and sync status will appear here.",
  "dashboard_models_title": "Models",
  "dashboard_models_description": "Assign models to SDD phases and agents.",
  "dashboard_models_action": "Manage Models",
  "dashboard_profiles_title": "Profiles",
  "dashboard_profiles_description": "Create and switch OpenCode SDD profiles.",
  "dashboard_profiles_action": "Manage Profiles",
  "dashboard_backups_title": "Backups",
  "dashboard_backups_description": "View and restore Gentle-AI backups.",
  "dashboard_backups_action": "View Backups",
  "dashboard_header_description": "Manage your Gentle-AI configuration, models, profiles, and backups from one place.",
  "dashboard_stat_models_label": "Active Models",
  "dashboard_stat_profiles_label": "Total Profiles",
  "dashboard_stat_backups_label": "Backups Stored",
  "dashboard_stat_system_label": "Last Sync",
  "dashboard_quick_access_title": "Quick Access",
  "dashboard_agents_title": "Installed agents",
  "dashboard_agents_manage": "Manage all",
  "dashboard_agent_configured": "Configured",
  "dashboard_agent_partial": "Partial",
  "dashboard_agent_add": "Add agent",
  "dashboard_agent_models": "models",
  "dashboard_agent_model_label": "model",
  "dashboard_last_sync_never": "Never",
  "dashboard_status_badge": "Active",
  "quick_action_models_title": "Configure models",
  "quick_action_models_desc": "Assign models to SDD phases",
  "quick_action_profiles_title": "Switch SDD profile",
  "quick_action_profiles_desc": "gentle-orchestrator active",
  "quick_action_backups_title": "Restore backup",
  "quick_action_backups_desc": "5 snapshots available",
  "tdd_strict_mode_title": "TDD strict mode",
  "tdd_strict_mode_desc": "Tests are enforced across all SDD phases in this workspace.",
  "tdd_strict_mode_enabled": "Enabled",
  "models_title": "Models",
  "models_status_badge": "Active",
  "models_header_description": "Assign models to SDD phases and agents.",
  "models_cardTitle": "Model Assignments",
  "models_loading": "Loading model assignments…",
  "models_loadError": "Failed to load model assignments",
  "models_validationUnavailable": "Model catalog unavailable",
  "models_validationMessage": "Selections cannot be validated until the catalog loads.",
  "profiles_title": "SDD Profiles",
  "profiles_status_badge": "Active",
  "profiles_header_description": "Create and switch OpenCode SDD profiles.",
  "profiles_cardTitle": "Profiles",
  "profiles_loading": "Loading profiles…",
  "profiles_loadError": "Failed to load profiles",
  "profiles_create_title": "Create Profile",
  "profiles_create_description": "Define a new profile and assign its model orchestrator.",
  "profiles_create_placeholder": "Profile name",
  "profiles_create_required": "The orchestrator assignment is required.",
  "profiles_create_action": "Create profile",
  "profiles_orchestrator_assignment": "Orchestrator assignment",
  "profiles_assigned": "Assigned",
  "profiles_saveAssignment": "Save assignment",
  "profiles_clear": "Clear",
  "profiles_discard": "Discard",
  "profiles_active": "Active",
  "profiles_modelAssignments": "model assignment",
  "profiles_modelAssignments_plural": "model assignments",
  "profiles_switch": "Switch",
  "profiles_delete": "Delete",
  "profiles_deleteConfirm": "Delete profile \"{{name}}\"?",
  "profiles_edit": "Edit",
  "profiles_editTitle": "Edit Profile",
  "profiles_save": "Save",
  "backups_title": "Backups",
  "backups_status_badge": "Active",
  "backups_header_description": "View and restore Gentle-AI backups.",
  "backups_cardTitle": "Backups",
  "backups_loading": "Loading backups…",
  "backups_loadError": "Failed to load backups",
  "backups_sync_title": "Sync Backups",
  "backups_sync_description": "Run a manual sync with the Gentle-AI backup store.",
  "backups_sync_action": "Run Sync",
  "backups_sync_running": "Sync running…",
  "backups_exitCode": "Exit code",
  "backups_noBackups": "No backups found",
  "backups_pinned": "Pinned",
  "backups_source": "Source",
  "backups_files": "files",
  "backups_restore": "Restore",
  "backups_pin": "Pin",
  "backups_unpin": "Unpin",
  "backups_delete": "Delete",
  "backups_cancel": "Cancel",
  "backups_deleteConfirmTitle": "Delete Backup",
  "backups_deleteConfirmDesc": "Are you sure you want to delete backup {{id}}? This action cannot be undone.",
  "backups_restoreConfirmTitle": "Restore Backup",
  "backups_restoreConfirmDesc": "This will restore backup {{id}} to its original location. Existing files may be overwritten. Continue?",
  "backups_restore_success": "Backup restored successfully.",
  "backups_delete_success": "Backup deleted successfully.",
  "backups_sync_success": "Backup sync completed.",
  "backups_sync_failed": "Backup sync failed.",
  "backups_pin_success": "Backup pinned.",
  "backups_unpin_success": "Backup unpinned.",
  "modelPicker_provider": "Provider",
  "modelPicker_model": "Model",
  "modelPicker_variant": "Variant",
  "modelPicker_save": "Save Assignment",
  "agentAssignment_unset": "unset",
  "agentAssignment_edit": "Edit assignment",
  "errors_generic": "Error",
  "dashboard_partial_error": "Some services could not be loaded. Showing available data.",
  "models_activeProfile": "Active Profile",
  "models_syncNow": "Sync Now",
  "models_resetAll": "Reset All",
  "models_resetConfirmTitle": "Reset All Assignments",
  "models_resetConfirmDesc": "This will reset all model assignments to their original values. Continue?",
  "models_syncSuccess": "Sync completed successfully",
  "models_emptyAssignmentsTitle": "No agent assignments found",
  "models_emptyAssignmentsDesc": "Sync configs or create an assignment source so models can appear here.",
};
