import type { Resources } from "./types";

export const en: Resources = {
  "nav_dashboard": "Dashboard",
  "nav_models": "Models",
  "nav_profiles": "Profiles",
  "nav_backups": "Backups",
  "footer_brand": "PreSett — Gentle-AI configuration manager",
  "topbar_search_placeholder": "Search agents, models, profiles…",
  "topbar_theme_toggle_aria": "Toggle theme",
  "topbar_notifications_aria": "Notifications",
  "topbar_account_aria": "Account",
  "topbar_menu_aria": "Open menu",
  "sidebar_group_menu": "Menu",
  "sidebar_group_workspace": "Workspace",
  "sidebar_sync_cta": "Sync configs",
  "workspace_overview": "Workspace overview",
  "dashboard_title": "Dashboard",
  "dashboard_status_title": "Status",
  "dashboard_status_description": "Gentle-AI configuration manager is ready.",
  "dashboard_status_hint": "Agent detection and sync status will appear here.",
  "dashboard_models_title": "Models",
  "dashboard_models_description": "Assign models to SDD phases and agents.",
  "dashboard_models_action": "Manage Models",
  "dashboard_profiles_title": "Profiles",
  "dashboard_profiles_description": "Create and switch OpenCode SDD profiles.",
  "dashboard_profiles_action": "Manage Profiles",
  "dashboard_backups_title": "Backups",
  "dashboard_backups_description": "View and restore Gentle-AI backups.",
  "dashboard_backups_action": "View Backups",
  "dashboard_header_description": "Manage your Gentle-AI configuration, models, profiles, and backups from one place.",
  "dashboard_stat_models_label": "Active Models",
  "dashboard_stat_profiles_label": "Total Profiles",
  "dashboard_stat_backups_label": "Backups Stored",
  "dashboard_stat_system_label": "System Status",
  "dashboard_quick_access_title": "Quick Access",
  "dashboard_status_badge": "Active",
  "quick_action_models_title": "Configure models",
  "quick_action_models_desc": "Assign models to SDD phases",
  "quick_action_profiles_title": "Switch SDD profile",
  "quick_action_profiles_desc": "gentle-orchestrator active",
  "quick_action_backups_title": "Restore backup",
  "quick_action_backups_desc": "5 snapshots available",
  "tdd_strict_mode_title": "TDD strict mode",
  "tdd_strict_mode_desc": "Tests are enforced across all SDD phases in this workspace.",
  "tdd_strict_mode_enabled": "Enabled",
  "models_title": "Models",
  "profiles_title": "SDD Profiles",
  "backups_title": "Backups",
  "errors_generic": "Error",
};
