import type { Resources } from "./types";

export const es: Resources = {
  "nav_dashboard": "Panel de control",
  "nav_models": "Modelos",
  "nav_profiles": "Perfiles SDD",
  "nav_backups": "Backups",
  "nav_diagnostics": "Diagnósticos",
  "nav_config": "Configuración",
  "nav_settings": "Configuración",
  "footer_brand": "PreSett — Gestor de configuración Gentle-AI",
  "topbar_search_placeholder": "Buscar en PreSett…",
  "topbar_search_aria": "Buscar agentes, modelos y perfiles",
  "topbar_search_clear_aria": "Limpiar búsqueda",
  "topbar_theme_toggle_aria": "Cambiar tema",
  "topbar_notifications_aria": "Notificaciones",
  "topbar_account_aria": "Cuenta",
  "topbar_menu_aria": "Abrir menú",
  "topbar_menu_close_aria": "Cerrar menú",
  "sidebar_group_menu": "Menú",
  "sidebar_group_workspace": "Espacio de trabajo",
  "sidebar_workspace_name": "Gentleman Stack",
  "sidebar_workspace_preset": "full-gentleman",
  "sidebar_gentle_ai_label": "Gentle-AI",
  "sidebar_sync_cta": "Sincronizar configs",
  "sidebar_sync_error_message": "No se pudo completar la sincronización de configuración. Intenta de nuevo o revisa el servicio de backups.",
  "sidebar_sync_success": "Sincronización de configuración completada.",
  "workspace_overview": "Resumen del espacio de trabajo",
  "dashboard_title": "Panel",
  "dashboard_status_title": "Estado",
  "dashboard_status_description": "El gestor de configuración Gentle-AI está listo.",
  "dashboard_status_hint": "Aquí aparecerá el estado de detección de agentes y sincronización.",
  "dashboard_models_title": "Modelos",
  "dashboard_models_description": "Asigna modelos a fases SDD y agentes.",
  "dashboard_models_action": "Gestionar Modelos",
  "dashboard_profiles_title": "Perfiles",
  "dashboard_profiles_description": "Crea y cambia entre perfiles SDD de OpenCode.",
  "dashboard_profiles_action": "Gestionar Perfiles",
  "dashboard_backups_title": "Backups",
  "dashboard_backups_description": "Ver y restaurar backups de Gentle-AI.",
  "dashboard_backups_action": "Ver Backups",
  "dashboard_header_description": "Gestiona tu configuración Gentle-AI, modelos, perfiles y backups desde un solo lugar.",
  "dashboard_stat_models_label": "Modelos Activos",
  "dashboard_stat_profiles_label": "Perfiles Totales",
  "dashboard_stat_backups_label": "Backups Guardados",
  "dashboard_stat_system_label": "Última Sincronización",
  "dashboard_gentle_ai_version": "Versión de Gentle-AI",
  "dashboard_quick_access_title": "Acceso Rápido",
  "dashboard_agents_title": "Agentes instalados",
  "dashboard_agents_manage": "Gestionar todos",
  "dashboard_agent_configured": "Configurado",
  "dashboard_agent_partial": "Parcial",
  "dashboard_agent_add": "Añadir agente",
  "dashboard_agent_models": "modelos",
  "dashboard_agent_model_label": "modelo",
  "dashboard_last_sync_never": "Nunca",
  "dashboard_status_badge": "Activo",
  "quick_action_models_title": "Configurar modelos",
  "quick_action_models_desc": "Asignar modelos a fases SDD",
  "quick_action_profiles_title": "Cambiar perfil SDD",
  "quick_action_profiles_desc": "gentle-orchestrator activo",
  "quick_action_backups_title": "Restaurar backup",
  "quick_action_backups_desc": "5 snapshots disponibles",
  "tdd_strict_mode_title": "Modo estricto TDD",
  "tdd_strict_mode_desc": "Las pruebas están aplicadas en todas las fases SDD de este espacio de trabajo.",
  "tdd_strict_mode_enabled": "Habilitado",
  "models_title": "Modelos",
  "models_status_badge": "Activo",
  "models_header_description": "Asigna modelos a fases SDD y agentes.",
  "models_cardTitle": "Asignaciones de Modelos",
  "models_loading": "Cargando asignaciones de modelos…",
  "models_loadError": "Error al cargar asignaciones de modelos",
  "models_validationUnavailable": "Catálogo de modelos no disponible",
  "models_validationMessage": "Las selecciones no se pueden validar hasta que cargue el catálogo.",
  "profiles_title": "Perfiles SDD",
  "profiles_status_badge": "Activo",
  "profiles_header_description": "Crea y cambia entre perfiles SDD de OpenCode.",
  "profiles_cardTitle": "Perfiles",
  "profiles_loading": "Cargando perfiles…",
  "profiles_loadError": "Error al cargar perfiles",
  "profiles_create_title": "Crear Perfil",
  "profiles_create_description": "Define un nuevo perfil y asigna su orquestador de modelos.",
  "profiles_create_placeholder": "Nombre del perfil",
  "profiles_create_required": "La asignación del orquestador es obligatoria.",
  "profiles_create_action": "Crear perfil",
  "profiles_name_required": "El nombre es obligatorio.",
  "profiles_save_profile": "GUARDAR PERFIL",
  "profiles_orchestrator_assignment": "Asignación del orquestador",
  "profiles_assigned": "Asignado",
  "profiles_saveAssignment": "Guardar asignación",
  "profiles_clear": "Limpiar",
  "profiles_discard": "Descartar",
  "profiles_active": "Activo",
  "profiles_modelAssignments": "asignación de modelo",
  "profiles_modelAssignments_plural": "asignaciones de modelos",
  "profiles_switch": "Cambiar",
  "profiles_delete": "Eliminar",
  "profiles_deleteConfirm": "¿Eliminar el perfil \"{{name}}\"?",
  "profiles_edit": "Editar",
  "profiles_editTitle": "Editar Perfil",
  "profiles_save": "Guardar",
  "profiles_nameHelp": "Usa letras minúsculas, números, guiones bajos o guiones. Otros caracteres se eliminan automáticamente.",
  "profiles_createDisabledHelp": "Agrega un nombre de perfil válido y una asignación de orquestador para habilitar la creación del perfil.",
  "profiles_createSuccess": "Perfil creado.",
  "profiles_createError": "No se pudo crear el perfil",
  "profiles_switchSuccess": "Perfil cambiado.",
  "profiles_deleteSuccess": "Perfil eliminado.",
  "profiles_deleteError": "No se pudo eliminar el perfil",
  "profiles_updateSuccess": "Perfil actualizado.",
  "profiles_updateError": "No se pudo actualizar el perfil",
  "backups_title": "Backups",
  "backups_status_badge": "Activo",
  "backups_header_description": "Ver y restaurar backups de Gentle-AI.",
  "backups_cardTitle": "Backups",
  "backups_loading": "Cargando backups…",
  "backups_loadError": "Error al cargar backups",
  "backups_sync_title": "Sincronizar Backups",
  "backups_sync_description": "Ejecuta una sincronización manual con el almacén de backups de Gentle-AI.",
  "backups_sync_action": "Ejecutar Sync",
  "backups_sync_running": "Sincronizando…",
  "backups_exitCode": "Código de salida",
  "backups_noBackups": "No se encontraron backups",
  "backups_pinned": "Fijado",
  "backups_source": "Origen",
  "backups_files": "archivos",
  "backups_restore": "Restaurar",
  "backups_pin": "Fijar",
  "backups_unpin": "Desfijar",
  "backups_delete": "Eliminar",
  "backups_cancel": "Cancelar",
  "backups_deleteConfirmTitle": "Eliminar Backup",
  "backups_deleteConfirmDesc": "¿Estás seguro de que quieres eliminar el backup {{id}}? Esta acción no se puede deshacer.",
  "backups_restoreConfirmTitle": "Restaurar Backup",
  "backups_restoreConfirmDesc": "Esto restaurará el backup {{id}} a su ubicación original. Los archivos existentes pueden ser sobrescritos. ¿Continuar?",
  "backups_restore_success": "✓ Restaurado {{name}}",
  "backups_delete_success": "Backup eliminado exitosamente.",
  "backups_sync_success": "Sincronización de backups completada.",
  "backups_sync_failed": "Falló la sincronización de backups.",
  "backups_pin_success": "Backup fijado.",
  "backups_unpin_success": "Backup desfijado.",
  "modelPicker_provider": "Proveedor",
  "modelPicker_model": "Modelo",
  "modelPicker_variant": "Variante",
  "modelPicker_save": "Guardar Asignación",
  "agentAssignment_unset": "no definido",
  "agentAssignment_edit": "Editar asignación",
  "errors_generic": "Error",
  "dashboard_partial_error": "Algunos servicios no pudieron cargarse. Mostrando datos disponibles.",
  "models_activeProfile": "Perfil Activo",
  "models_syncNow": "Sincronizar Ahora",
  "models_resetAll": "Restablecer Todo",
  "models_resetConfirmTitle": "Restablecer Todas las Asignaciones",
  "models_resetConfirmDesc": "Esto restablecerá todas las asignaciones de modelos a sus valores originales. ¿Continuar?",
  "models_syncSuccess": "Sincronización completada exitosamente",
  "models_assignmentSaved": "Asignación guardada.",
  "models_assignmentSaveError": "No se pudo guardar la asignación",
  "models_profileSwitched": "Perfil cambiado.",
  "models_profileSwitchError": "No se pudo cambiar el perfil",
  "models_resetSuccess": "Asignaciones restablecidas.",
  "models_emptyAssignmentsTitle": "No hay asignaciones de agentes",
  "models_emptyAssignmentsDesc": "Sincroniza la configuración o crea una fuente de asignaciones para que los modelos aparezcan aquí.",
  "diagnostics_update_notice": "Gentle-AI {{version}} está disponible en {{channel}}.",
  "diagnostics_check_now": "Comprobar releases de Gentle-AI ahora",
  "diagnostics_checking": "Comprobando releases…",
  "diagnostics_title": "Diagnósticos",
  "diagnostics_status_badge": "Local",
  "diagnostics_header_description": "Revisa el estado seguro de Gentle-AI y las versiones disponibles sin exponer rutas locales.",
  "diagnostics_loading": "Cargando diagnósticos…",
  "diagnostics_load_error": "No se pudieron cargar los diagnósticos.",
  "diagnostics_cli_title": "CLI Gentle-AI",
  "diagnostics_config_title": "Configuración",
  "diagnostics_state_title": "Estado",
  "diagnostics_routes_title": "Rutas canónicas",
  "diagnostics_installed": "Instalada",
  "diagnostics_unavailable": "No disponible",
  "diagnostics_available": "Disponible",
  "diagnostics_route_config": "Archivo de configuración",
  "diagnostics_route_state": "Archivo de estado",
  "diagnostics_route_backups": "Directorio de backups",
  "diagnostics_exists": "Existe",
  "diagnostics_readable": "Legible",
  "diagnostics_writable": "Escribible",
  "diagnostics_yes": "Sí",
  "diagnostics_no": "No",
  "diagnostics_releases_title": "Releases de Gentle-AI",
  "diagnostics_stable": "Stable",
  "diagnostics_rc": "Release candidate",
  "diagnostics_no_update": "No hay actualización pendiente",
  "diagnostics_check_error": "No se pudo completar la comprobación de releases.",
  "config_title": "Configuración global",
  "config_description": "Gestiona las preferencias de Gentle-AI y OpenCode de forma independiente.",
  "config_loading": "Cargando configuración…",
  "config_load_error": "No se pudo cargar la configuración.",
  "config_status_ready": "Configurado",
  "config_status_incomplete": "Requiere configuración",
  "config_gentle_title": "Gentle-AI",
  "config_gentle_description": "Define el idioma de respuesta y la persona para este espacio de trabajo.",
  "config_gentle_status": "Espacio de trabajo",
  "config_language": "Idioma de respuesta",
  "config_persona": "Persona",
  "config_gentle_save": "Guardar Gentle-AI",
  "config_gentle_saved": "Configuración de Gentle-AI guardada.",
  "config_gentle_error": "No se pudo guardar la configuración de Gentle-AI.",
  "config_opencode_title": "OpenCode",
  "config_opencode_description": "Elige la asignación de agente predeterminada para OpenCode.",
  "config_agent": "Agente",
  "config_provider": "Proveedor",
  "config_model": "Modelo",
  "config_variant": "Variante",
  "config_catalog_error": "El catálogo de modelos no está disponible. La configuración de modelos está deshabilitada.",
  "config_opencode_save": "Guardar OpenCode",
  "config_opencode_saved": "Configuración de OpenCode guardada.",
  "config_opencode_error": "No se pudo guardar la configuración de OpenCode.",
  "config_field_required": "Este campo es obligatorio.",
  "search_title": "Búsqueda global",
  "search_status_badge": "Local",
  "search_header_description": "Encuentra agentes, modelos, perfiles, backups y campos seguros de configuración desde una sola página.",
  "search_empty_title": "Busca en todo PreSett",
  "search_empty_description": "Busca agentes, modelos, perfiles, backups y campos seguros de configuración.",
  "search_loading": "Buscando…",
  "search_no_results": "No se encontraron resultados para \"{{query}}\".",
  "search_error_fallback": "No se pudo cargar la búsqueda.",
  "search_partial_warning": "Algunas fuentes de búsqueda no estuvieron disponibles: {{sources}}.",
  "search_group_agent": "Agentes",
  "search_group_model": "Modelos",
  "search_group_profile": "Perfiles",
  "search_group_backup": "Backups",
  "search_group_config": "Configuración",
  "search_pinned": "Fijado",
  "search_active": "Activo",
  "notif_update_title": "Actualización disponible",
  "notif_update_available": "Gentle AI {{version}} está listo para instalar.",
  "notif_panel_title": "Notificaciones",
  "notif_panel_empty": "Aún no hay notificaciones.",
  "notif_item_dismiss_aria": "Descartar",
  "listing_search_placeholder": "Buscar…",
  "listing_search_aria": "Buscar en listados",
  "listing_sort_label": "Ordenar por",
  "listing_sort_name": "Nombre",
  "listing_sort_date": "Fecha",
  "listing_sort_size": "Tamaño",
  "listing_sort_fileCount": "Cantidad de archivos",
  "listing_sort_direction_aria": "Dirección de orden",
  "listing_sort_agent": "Agente",
  "listing_sort_provider": "Proveedor",
  "listing_sort_model": "Modelo",
  "listing_sort_variant": "Variante",
  "listing_sort_active": "Activo",
  "listing_sort_lastUpdated": "Ultima actualizacion",
  "listing_filter_agent": "Agente",
  "listing_filter_agent_openai": "OpenAI",
  "listing_filter_agent_anthropic": "Anthropic",
  "listing_filter_provider": "Proveedor",
  "listing_filter_model": "Modelo",
  "listing_filter_variant": "Variante",
  "listing_filter_pinned": "Fijado",
  "listing_active_filters": "{{count}} filtros activos",
  "listing_clear_filters": "Limpiar filtros",
  "listing_no_data_models": "No hay asignaciones de modelos",
  "listing_no_data_models_desc": "Sincroniza la configuración o crea una fuente de asignaciones para que los modelos aparezcan aquí.",
  "listing_no_data_profiles": "Aún no hay perfiles",
  "listing_no_data_profiles_desc": "Crea un perfil para comenzar.",
  "listing_no_data_backups": "No se encontraron backups",
  "listing_no_data_backups_desc": "Ejecuta una sincronización para descubrir backups disponibles.",
  "listing_no_matches_models": "No hay modelos coincidentes",
  "listing_no_matches_models_desc": "Intenta ajustar tus filtros para encontrar lo que buscas.",
  "listing_no_matches_profiles": "No hay perfiles coincidentes",
  "listing_no_matches_profiles_desc": "Intenta ajustar tu búsqueda para encontrar lo que buscas.",
  "listing_no_matches_backups": "No hay backups coincidentes",
  "listing_no_matches_backups_desc": "Intenta ajustar tus filtros para encontrar lo que buscas.",
  "listing_clear_action": "Limpiar",
};
