import type { Resources } from "./types";

export const es: Resources = {
  "nav_dashboard": "Panel de control",
  "nav_models": "Modelos",
  "nav_profiles": "Perfiles",
  "nav_backups": "Backups",
  "footer_brand": "PreSett — Gestor de configuración Gentle-AI",
  "topbar_search_placeholder": "Buscar agentes, modelos, perfiles…",
  "topbar_theme_toggle_aria": "Cambiar tema",
  "topbar_notifications_aria": "Notificaciones",
  "topbar_account_aria": "Cuenta",
  "topbar_menu_aria": "Abrir menú",
  "sidebar_group_menu": "Menú",
  "sidebar_group_workspace": "Espacio de trabajo",
  "sidebar_sync_cta": "Sincronizar configs",
  "workspace_overview": "Resumen del espacio de trabajo",
  "dashboard_title": "Panel",
  "dashboard_status_title": "Estado",
  "dashboard_status_description": "El gestor de configuración Gentle-AI está listo.",
  "dashboard_status_hint": "Aquí aparecerá el estado de detección de agentes y sincronización.",
  "dashboard_models_title": "Modelos",
  "dashboard_models_description": "Asigna modelos a fases SDD y agentes.",
  "dashboard_models_action": "Gestionar Modelos",
  "dashboard_profiles_title": "Perfiles",
  "dashboard_profiles_description": "Crea y cambia entre perfiles SDD de OpenCode.",
  "dashboard_profiles_action": "Gestionar Perfiles",
  "dashboard_backups_title": "Backups",
  "dashboard_backups_description": "Ver y restaurar backups de Gentle-AI.",
  "dashboard_backups_action": "Ver Backups",
  "dashboard_header_description": "Gestiona tu configuración Gentle-AI, modelos, perfiles y backups desde un solo lugar.",
  "dashboard_stat_models_label": "Modelos Activos",
  "dashboard_stat_profiles_label": "Perfiles Totales",
  "dashboard_stat_backups_label": "Backups Guardados",
  "dashboard_stat_system_label": "Estado del Sistema",
  "dashboard_quick_access_title": "Acceso Rápido",
  "dashboard_status_badge": "Activo",
  "quick_action_models_title": "Configurar modelos",
  "quick_action_models_desc": "Asignar modelos a fases SDD",
  "quick_action_profiles_title": "Cambiar perfil SDD",
  "quick_action_profiles_desc": "gentle-orchestrator activo",
  "quick_action_backups_title": "Restaurar backup",
  "quick_action_backups_desc": "5 snapshots disponibles",
  "tdd_strict_mode_title": "Modo estricto TDD",
  "tdd_strict_mode_desc": "Las pruebas están aplicadas en todas las fases SDD de este espacio de trabajo.",
  "tdd_strict_mode_enabled": "Habilitado",
  "models_title": "Modelos",
  "profiles_title": "Perfiles SDD",
  "backups_title": "Backups",
  "errors_generic": "Error",
};
