import type { Resources } from "./types";

export const es: Resources = {
  "nav_dashboard": "Panel de control",
  "nav_models": "Modelos",
  "nav_profiles": "Perfiles",
  "nav_backups": "Backups",
  "footer_brand": "PreSett — Gestor de configuración Gentle-AI",
  "topbar_search_placeholder": "Buscar agentes, modelos, perfiles…",
  "topbar_theme_toggle_aria": "Cambiar tema",
  "topbar_notifications_aria": "Notificaciones",
  "topbar_account_aria": "Cuenta",
  "topbar_menu_aria": "Abrir menú",
  "sidebar_group_menu": "Menú",
  "sidebar_group_workspace": "Espacio de trabajo",
  "sidebar_sync_cta": "Sincronizar configs",
  "workspace_overview": "Resumen del espacio de trabajo",
  "dashboard_title": "Panel",
  "dashboard_status_title": "Estado",
  "dashboard_status_description": "El gestor de configuración Gentle-AI está listo.",
  "dashboard_status_hint": "Aquí aparecerá el estado de detección de agentes y sincronización.",
  "dashboard_models_title": "Modelos",
  "dashboard_models_description": "Asigna modelos a fases SDD y agentes.",
  "dashboard_models_action": "Gestionar Modelos",
  "dashboard_profiles_title": "Perfiles",
  "dashboard_profiles_description": "Crea y cambia entre perfiles SDD de OpenCode.",
  "dashboard_profiles_action": "Gestionar Perfiles",
  "dashboard_backups_title": "Backups",
  "dashboard_backups_description": "Ver y restaurar backups de Gentle-AI.",
  "dashboard_backups_action": "Ver Backups",
  "dashboard_header_description": "Gestiona tu configuración Gentle-AI, modelos, perfiles y backups desde un solo lugar.",
  "dashboard_stat_models_label": "Modelos Activos",
  "dashboard_stat_profiles_label": "Perfiles Totales",
  "dashboard_stat_backups_label": "Backups Guardados",
  "dashboard_stat_system_label": "Última Sincronización",
  "dashboard_quick_access_title": "Acceso Rápido",
  "dashboard_agents_title": "Agentes instalados",
  "dashboard_agents_manage": "Gestionar todos",
  "dashboard_agent_configured": "Configurado",
  "dashboard_agent_partial": "Parcial",
  "dashboard_agent_add": "Añadir agente",
  "dashboard_agent_models": "modelos",
  "dashboard_agent_model_label": "modelo",
  "dashboard_last_sync_never": "Nunca",
  "dashboard_status_badge": "Activo",
  "quick_action_models_title": "Configurar modelos",
  "quick_action_models_desc": "Asignar modelos a fases SDD",
  "quick_action_profiles_title": "Cambiar perfil SDD",
  "quick_action_profiles_desc": "gentle-orchestrator activo",
  "quick_action_backups_title": "Restaurar backup",
  "quick_action_backups_desc": "5 snapshots disponibles",
  "tdd_strict_mode_title": "Modo estricto TDD",
  "tdd_strict_mode_desc": "Las pruebas están aplicadas en todas las fases SDD de este espacio de trabajo.",
  "tdd_strict_mode_enabled": "Habilitado",
  "models_title": "Modelos",
  "models_status_badge": "Activo",
  "models_header_description": "Asigna modelos a fases SDD y agentes.",
  "models_cardTitle": "Asignaciones de Modelos",
  "models_loading": "Cargando asignaciones de modelos…",
  "models_loadError": "Error al cargar asignaciones de modelos",
  "models_validationUnavailable": "Catálogo de modelos no disponible",
  "models_validationMessage": "Las selecciones no se pueden validar hasta que cargue el catálogo.",
  "profiles_title": "Perfiles SDD",
  "profiles_status_badge": "Activo",
  "profiles_header_description": "Crea y cambia entre perfiles SDD de OpenCode.",
  "profiles_cardTitle": "Perfiles",
  "profiles_loading": "Cargando perfiles…",
  "profiles_loadError": "Error al cargar perfiles",
  "profiles_create_title": "Crear Perfil",
  "profiles_create_placeholder": "Nombre del perfil",
  "profiles_create_required": "La asignación del orquestador es obligatoria.",
  "profiles_create_action": "Crear Perfil",
  "profiles_active": "Activo",
  "profiles_modelAssignments": "asignación de modelo",
  "profiles_modelAssignments_plural": "asignaciones de modelos",
  "profiles_switch": "Cambiar",
  "profiles_delete": "Eliminar",
  "profiles_deleteConfirm": "¿Eliminar el perfil \"{{name}}\"?",
  "backups_title": "Backups",
  "backups_status_badge": "Activo",
  "backups_header_description": "Ver y restaurar backups de Gentle-AI.",
  "backups_cardTitle": "Backups",
  "backups_loading": "Cargando backups…",
  "backups_loadError": "Error al cargar backups",
  "backups_sync_title": "Sincronizar Backups",
  "backups_sync_description": "Ejecuta una sincronización manual con el almacén de backups de Gentle-AI.",
  "backups_sync_action": "Ejecutar Sync",
  "backups_sync_running": "Sincronizando…",
  "backups_exitCode": "Código de salida",
  "backups_noBackups": "No se encontraron backups",
  "backups_pinned": "Fijado",
  "backups_source": "Origen",
  "backups_files": "archivos",
  "backups_restore": "Restaurar",
  "backups_pin": "Fijar",
  "backups_unpin": "Desfijar",
  "backups_delete": "Eliminar",
  "backups_cancel": "Cancelar",
  "backups_deleteConfirmTitle": "Eliminar Backup",
  "backups_deleteConfirmDesc": "¿Estás seguro de que quieres eliminar el backup {{id}}? Esta acción no se puede deshacer.",
  "backups_restoreConfirmTitle": "Restaurar Backup",
  "backups_restoreConfirmDesc": "Esto restaurará el backup {{id}} a su ubicación original. Los archivos existentes pueden ser sobrescritos. ¿Continuar?",
  "modelPicker_provider": "Proveedor",
  "modelPicker_model": "Modelo",
  "modelPicker_variant": "Variante",
  "modelPicker_save": "Guardar Asignación",
  "agentAssignment_unset": "no definido",
  "agentAssignment_edit": "Editar asignación",
  "errors_generic": "Error",
  "dashboard_partial_error": "Algunos servicios no pudieron cargarse. Mostrando datos disponibles.",
};
